version: "3.1"
services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=mydb
    restart: always
    ports:
      - 5432:5432
  backend:
    tty: true
    stdin_open: true
    image: node:16
    container_name: backend
    build: server/
    restart: always
    ports:
      - 3333:3333
    environment:
      - DB_HOST=database
      - DATABASE_URL=postgresql://postgres:postgrespassword@database:5432/mydb
      - JWT_SECRET=senha_secreta
    depends_on:
      - "database"
    command: bash -c "npx prisma generate && npx prisma migrate dev && npm run dev"
  frontend:
    image: node:16
    container_name: frontend
    build: web/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend
    command: bash -c "npm run dev"

networks:
  default:
    driver: bridge
