version: "3"
services:
  frontend:
    image: node:latest
    container_name: frontend_container
    build: web/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./web:/usr/app
    command: bash -c "npm install && npm run dev"
  backend:
    image: node:latest
    container_name: backend_container
    build: server/
    restart: always
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/mydb?schema=public
      - JWT_SECRET=senha_secreta
    depends_on:
      - database
    volumes:
      - ./server:/usr/app
    command: bash -c "npm install && npm run dev"
  database:
    image: postgres
    container_name: database_container
    # env_file:
    #   - ./.env
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=mydb
    restart: always
    ports:
      - 2345:5432
